#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// Читаем package.json для получения версии
const packageJsonPath = path.join(__dirname, '../package.json');
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

// Получаем текущую дату в ISO формате
const buildDate = new Date().toISOString();

// Формируем содержимое .env.local
const envContent = `# Auto-generated by scripts/update-version.cjs
VITE_APP_VERSION=${packageJson.version}
VITE_BUILD_DATE=${buildDate}
`;

// Записываем в .env.local
const envPath = path.join(__dirname, '../.env.local');
fs.writeFileSync(envPath, envContent);

console.log(`✅ Версия обновлена: v${packageJson.version} • ${new Date(buildDate).toLocaleDateString('ru-RU', {
  day: '2-digit',
  month: '2-digit',
  year: 'numeric'
})}`);
